<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TP04A.Participant</RootNamespace>
    <AssemblyName>TP04A.Participant</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contracts\TP04A.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\src\Enterprise.Shared\Enterprise.Shared.csproj" />
  </ItemGroup>

</Project>
